version: "3"
services:
  db_students:
    image: postgres
    container_name: db_students
    restart: always
    ports:
      - 1234:5432
    env_file:
      - back-end/.env
    volumes:
      - pg_students:/var/lib/postgresql/data

  node_app_students:
    container_name: node_app_students
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_students
    env_file:
      - back-end/.env

  app_react:
    container_name: app_react
    build: ./front-end
    volumes:
      - build_front:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_front:/var/www/html
    depends_on:
      - app_react
      - db_students
      - node_app_students

volumes:
  pg_students:
  build_front:
