version: "3"
services:
  db_test:
    image: postgres
    container_name: db_test
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./back-end/env.test

  node_app_test:
    container_name: node_app_test
    build: ./back-end
    ports:
      - 5000:5000
    env_file:
      - ./back-end/env.test
    depends_on:
      - db_test
